### ISSUE TITLE
'--isolatedModules' flag + @ionic/core = no no

### ISSUE THREAD

**Issue by jeroensak** [ionic-team/ionic-react-conference-app#1]
On master commit `c0d5dfdb931ee0cbf1eaedfcfbb7411dbcb82692` (currently latest) when clean installing node packages and starting the app, TypeScript throws the following error:
```
/ionic-react-conference-app/node_modules/@ionic/core/dist/types/components/nav/view-controller.d.ts
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

    1 | import { ComponentProps, FrameworkDelegate } from '../../interface';
  > 2 | export declare const enum ViewState {
      |                           ^
    3 |     New = 1,
    4 |     Attached = 2,
    5 |     Destroyed = 3
```

This happens after a clean install and start using TypeScript 3.1.6 (as defined in the package.json) on node 10.13.0 and npm 6.4.1. 

Is this something that you recognize?

**Comment by dayaki** [comment]
Just wondering, your app never emit the error `Cannot find module '@ionic/react`??

**Comment by jeroensak** [comment]
@dayaki No it isn't, but my issue is fixed.
