### ISSUE TITLE
Cannot run ionix serve because: Could not find a required file Name: index.html

### ISSUE THREAD

**Issue by anesuc** [ionic-team/ionic-react-conference-app#121]
Hi all,

As mentioned in the title I am getting this error when I try to run this based on the given instructions. Any ideas?

Thanks

**Comment by mcbeltran** [comment]
I copied the index.html in the main folder to public folder and it worked for me. I also renamed main.tsx to index.tsx

**Comment by anesuc** [comment]
I ended up figuring it out. I had to do several workarounds which I am not sure are correct. I copied the index.html, index.js etc from https://github.com/facebook/create-react-app/tree/main/packages/cra-template/template . ionic serve did run but had errors about assets so I copied the entire assets folder into src and that resolved it. Pretty confident thats not the best solution but that's the only way I got it to work
