### ISSUE TITLE
Still buggy?

### ISSUE THREAD

**Issue by latifs** [ionic-team/ionic-react-conference-app#33]
Hi Guys,
is it me or is the app still somewhat buggy?

I cannot seem to be able to access the Account, Support or logout pages or Login for that matter. 
The tutorial Button is also inactive.

I'd like to start using react with ionic, and this boilerplate in particular, I just want to make sure this is an option though.

Thanks for the hard work

**Comment by brandyscarney** [comment]
Thanks for the issue! We just pushed a ton of changes to update this to Ionic 5 and fixed some bugs. Could you let us know if you still have issues?
