### ISSUE TITLE
Src > theme.css file seems to be an unwanted file

### ISSUE THREAD

**Issue by harishmaddali** [ionic-team/ionic-react-conference-app#36]
There is a similar file under `src > theme > variables.css` which covers everything `src > theme.css` contains. `ionic serve` also doesn't looks for changes made to `theme.css` file. So I think it is safe to remove `theme.css` file from the repo.

**Comment by brandyscarney** [comment]
Thank you! This will be removed in this PR: https://github.com/ionic-team/ionic-react-conference-app/pull/39
