### ISSUE TITLE
Add test examples

### ISSUE THREAD

**Issue by garrensmith** [ionic-team/ionic-react-conference-app#6]
This project has been really helpful, thank you. Would you be able to add an example of how to unit test a react component that uses the @ionic/react library?

I've tried using jest and enzyme and I'm getting compile issues that I'm not sure on how to fix.

**Comment by jthoms1** [comment]
I have created some tests within ionic/react using jest and react-testing-library.  More details on how to write these tests can be found here: https://github.com/ionic-team/ionic/tree/master/react

**Comment by garrensmith** [comment]
Awesome thanks

**Comment by charithAmila** [comment]
> I have created some tests within ionic/react using jest and react-testing-library. More details on how to write these tests can be found here: https://github.com/ionic-team/ionic/tree/master/react

Did you remove this repository
